spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/products/**
            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders/**,/api/cart/**

#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true



server:
  port: 8080

